--- 
- 
  data: "CREATE TABLE `user` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `username` varchar(12) NOT NULL,\n  `password` varchar(256) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `username_UNIQUE` (`username`)\n) ENGINE=InnoDB AUTO_INCREMENT=1040 DEFAULT CHARSET=utf8"
  schema: user
