--- 
- 
  data: "CREATE TABLE `sessions` (\n  `id` char(72) NOT NULL,\n  `session_data` text,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8"
  schema: sessions
- 
  data: "CREATE TABLE `sessions2` (\n  `id` char(72) NOT NULL,\n  `session_data` text,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8"
  schema: sessions2
